pgsql:
  dbname: #####
  host: #####
  port: #####
  user: #####
  password: #####

mariadb:
  dbname: #####
  host: #####
  port: #####
  user: #####
  password: #####

rows_per_insert: {1000 | 10000}
dump_directory_path: './dump/origin'
clean_directory_path: './dump/clean'
dump: { tables | file }
clean: { tables | file | chunk }

scripts:
  global: { true | false }
  session: { true | false }
