pgsql:
  dbname: #####
  host: #####
  port: #####
  user: #####
  password: #####

mariadb:
  dbname: #####
  host: #####
  port: #####
  user: #####
  password: #####

dump: { tables | file }
clean: { tables | file | chunk }

scripts:
  global: { true | false }
  session: { true | false }